<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{

	private $_countries = [
		['country_name' =>  'Afghanistan', 'iso_code' => 'AF', 'iso_code_numeric' => '004'],
		['country_name' =>  'Åland islands', 'iso_code' => 'AX', 'iso_code_numeric' => '248'],
		['country_name' =>  'Albania', 'iso_code' => 'AL', 'iso_code_numeric' => '008'],
		['country_name' =>  'Algeria', 'iso_code' => 'DZ', 'iso_code_numeric' => '012'],
		['country_name' =>  'American samoa', 'iso_code' => 'AS', 'iso_code_numeric' => '016'],
		['country_name' =>  'Andorra', 'iso_code' => 'AD', 'iso_code_numeric' => '020'],
		['country_name' =>  'Angola', 'iso_code' => 'AO', 'iso_code_numeric' => '024'],
		['country_name' =>  'Anguilla', 'iso_code' => 'AI', 'iso_code_numeric' => '660'],
		['country_name' =>  'Antarctica', 'iso_code' => 'AQ', 'iso_code_numeric' => '010'],
		['country_name' =>  'Antigua and barbuda', 'iso_code' => 'AG', 'iso_code_numeric' => '028'],
		['country_name' =>  'Argentina', 'iso_code' => 'AR', 'iso_code_numeric' => '032'],
		['country_name' =>  'Armenia', 'iso_code' => 'AM', 'iso_code_numeric' => '051'],
		['country_name' =>  'Aruba', 'iso_code' => 'AW', 'iso_code_numeric' => '533'],
		['country_name' =>  'Australia', 'iso_code' => 'AU', 'iso_code_numeric' => '036'],
		['country_name' =>  'Austria', 'iso_code' => 'AT', 'iso_code_numeric' => '040'],
		['country_name' =>  'Azerbaijan', 'iso_code' => 'AZ', 'iso_code_numeric' => '031'],
		['country_name' =>  'Bahamas', 'iso_code' => 'BS', 'iso_code_numeric' => '044'],
		['country_name' =>  'Bahrain', 'iso_code' => 'BH', 'iso_code_numeric' => '048'],
		['country_name' =>  'Bangladesh', 'iso_code' => 'BD', 'iso_code_numeric' => '050'],
		['country_name' =>  'Barbados', 'iso_code' => 'BB', 'iso_code_numeric' => '052'],
		['country_name' =>  'Belarus', 'iso_code' => 'BY', 'iso_code_numeric' => '112'],
		['country_name' =>  'Belgium', 'iso_code' => 'BE', 'iso_code_numeric' => '056'],
		['country_name' =>  'Belize', 'iso_code' => 'BZ', 'iso_code_numeric' => '084'],
		['country_name' =>  'Benin', 'iso_code' => 'BJ', 'iso_code_numeric' => '204'],
		['country_name' =>  'Bermuda', 'iso_code' => 'BM', 'iso_code_numeric' => '060'],
		['country_name' =>  'Bhutan', 'iso_code' => 'BT', 'iso_code_numeric' => '064'],
		['country_name' =>  'Bolivia, plurinational state of', 'iso_code' => 'BO', 'iso_code_numeric' => '068'],
		['country_name' =>  'Bonaire, sint eustatius and saba', 'iso_code' => 'BQ', 'iso_code_numeric' => '535'],
		['country_name' =>  'Bosnia and herzegovina', 'iso_code' => 'BA', 'iso_code_numeric' => '070'],
		['country_name' =>  'Botswana', 'iso_code' => 'BW', 'iso_code_numeric' => '072'],
		['country_name' =>  'Bouvet island', 'iso_code' => 'BV', 'iso_code_numeric' => '074'],
		['country_name' =>  'Brazil', 'iso_code' => 'BR', 'iso_code_numeric' => '076'],
		['country_name' =>  'British indian ocean territory', 'iso_code' => 'IO', 'iso_code_numeric' => '086'],
		['country_name' =>  'Brunei darussalam', 'iso_code' => 'BN', 'iso_code_numeric' => '096'],
		['country_name' =>  'Bulgaria', 'iso_code' => 'BG', 'iso_code_numeric' => '100'],
		['country_name' =>  'Burkina faso', 'iso_code' => 'BF', 'iso_code_numeric' => '854'],
		['country_name' =>  'Burundi', 'iso_code' => 'BI', 'iso_code_numeric' => '108'],
		['country_name' =>  'Cambodia', 'iso_code' => 'KH', 'iso_code_numeric' => '116'],
		['country_name' =>  'Cameroon', 'iso_code' => 'CM', 'iso_code_numeric' => '120'],
		['country_name' =>  'Canada', 'iso_code' => 'CA', 'iso_code_numeric' => '124'],
		['country_name' =>  'Cape verde', 'iso_code' => 'CV', 'iso_code_numeric' => '132'],
		['country_name' =>  'Cayman islands', 'iso_code' => 'KY', 'iso_code_numeric' => '136'],
		['country_name' =>  'Central african republic', 'iso_code' => 'CF', 'iso_code_numeric' => '140'],
		['country_name' =>  'Chad', 'iso_code' => 'TD', 'iso_code_numeric' => '148'],
		['country_name' =>  'Chile', 'iso_code' => 'CL', 'iso_code_numeric' => '152'],
		['country_name' =>  'China', 'iso_code' => 'CN', 'iso_code_numeric' => '156'],
		['country_name' =>  'Christmas island', 'iso_code' => 'CX', 'iso_code_numeric' => '162'],
		['country_name' =>  'Cocos (keeling) islands', 'iso_code' => 'CC', 'iso_code_numeric' => '166'],
		['country_name' =>  'Colombia', 'iso_code' => 'CO', 'iso_code_numeric' => '170'],
		['country_name' =>  'Comoros', 'iso_code' => 'KM', 'iso_code_numeric' => '174'],
		['country_name' =>  'Congo', 'iso_code' => 'CG', 'iso_code_numeric' => '178'],
		['country_name' =>  'Congo, the democratic republic of the', 'iso_code' => 'CD', 'iso_code_numeric' => '180'],
		['country_name' =>  'Cook islands', 'iso_code' => 'CK', 'iso_code_numeric' => '184'],
		['country_name' =>  'Costa rica', 'iso_code' => 'CR', 'iso_code_numeric' => '188'],
		['country_name' =>  'Côte d\'ivoire', 'iso_code' => 'CI', 'iso_code_numeric' => '384'],
		['country_name' =>  'Croatia', 'iso_code' => 'HR', 'iso_code_numeric' => '191'],
		['country_name' =>  'Cuba', 'iso_code' => 'CU', 'iso_code_numeric' => '192'],
		['country_name' =>  'Curaçao', 'iso_code' => 'CW', 'iso_code_numeric' => '531'],
		['country_name' =>  'Cyprus', 'iso_code' => 'CY', 'iso_code_numeric' => '196'],
		['country_name' =>  'Czech republic', 'iso_code' => 'CZ', 'iso_code_numeric' => '203'],
		['country_name' =>  'Denmark', 'iso_code' => 'DK', 'iso_code_numeric' => '208'],
		['country_name' =>  'Djibouti', 'iso_code' => 'DJ', 'iso_code_numeric' => '262'],
		['country_name' =>  'Dominica', 'iso_code' => 'DM', 'iso_code_numeric' => '212'],
		['country_name' =>  'Dominican republic', 'iso_code' => 'DO', 'iso_code_numeric' => '214'],
		['country_name' =>  'Ecuador', 'iso_code' => 'EC', 'iso_code_numeric' => '218'],
		['country_name' =>  'Egypt', 'iso_code' => 'EG', 'iso_code_numeric' => '818'],
		['country_name' =>  'El salvador', 'iso_code' => 'SV', 'iso_code_numeric' => '222'],
		['country_name' =>  'Equatorial guinea', 'iso_code' => 'GQ', 'iso_code_numeric' => '226'],
		['country_name' =>  'Eritrea', 'iso_code' => 'ER', 'iso_code_numeric' => '232'],
		['country_name' =>  'Estonia', 'iso_code' => 'EE', 'iso_code_numeric' => '233'],
		['country_name' =>  'Ethiopia', 'iso_code' => 'ET', 'iso_code_numeric' => '231'],
		['country_name' =>  'Falkland islands (malvinas)', 'iso_code' => 'FK', 'iso_code_numeric' => '238'],
		['country_name' =>  'Faroe islands', 'iso_code' => 'FO', 'iso_code_numeric' => '234'],
		['country_name' =>  'Fiji', 'iso_code' => 'FJ', 'iso_code_numeric' => '242'],
		['country_name' =>  'Finland', 'iso_code' => 'FI', 'iso_code_numeric' => '246'],
		['country_name' =>  'France', 'iso_code' => 'FR', 'iso_code_numeric' => '250'],
		['country_name' =>  'French guiana', 'iso_code' => 'GF', 'iso_code_numeric' => '254'],
		['country_name' =>  'French polynesia', 'iso_code' => 'PF', 'iso_code_numeric' => '258'],
		['country_name' =>  'French southern territories', 'iso_code' => 'TF', 'iso_code_numeric' => '260'],
		['country_name' =>  'Gabon', 'iso_code' => 'GA', 'iso_code_numeric' => '266'],
		['country_name' =>  'Gambia', 'iso_code' => 'GM', 'iso_code_numeric' => '270'],
		['country_name' =>  'Georgia', 'iso_code' => 'GE', 'iso_code_numeric' => '268'],
		['country_name' =>  'Germany', 'iso_code' => 'DE', 'iso_code_numeric' => '276'],
		['country_name' =>  'Ghana', 'iso_code' => 'GH', 'iso_code_numeric' => '288'],
		['country_name' =>  'Gibraltar', 'iso_code' => 'GI', 'iso_code_numeric' => '292'],
		['country_name' =>  'Greece', 'iso_code' => 'GR', 'iso_code_numeric' => '300'],
		['country_name' =>  'Greenland', 'iso_code' => 'GL', 'iso_code_numeric' => '304'],
		['country_name' =>  'Grenada', 'iso_code' => 'GD', 'iso_code_numeric' => '308'],
		['country_name' =>  'Guadeloupe', 'iso_code' => 'GP', 'iso_code_numeric' => '312'],
		['country_name' =>  'Guam', 'iso_code' => 'GU', 'iso_code_numeric' => '316'],
		['country_name' =>  'Guatemala', 'iso_code' => 'GT', 'iso_code_numeric' => '320'],
		['country_name' =>  'Guernsey', 'iso_code' => 'GG', 'iso_code_numeric' => '831'],
		['country_name' =>  'Guinea', 'iso_code' => 'GN', 'iso_code_numeric' => '324'],
		['country_name' =>  'Guinea-bissau', 'iso_code' => 'GW', 'iso_code_numeric' => '624'],
		['country_name' =>  'Guyana', 'iso_code' => 'GY', 'iso_code_numeric' => '328'],
		['country_name' =>  'Haiti', 'iso_code' => 'HT', 'iso_code_numeric' => '332'],
		['country_name' =>  'Heard island and mcdonald islands', 'iso_code' => 'HM', 'iso_code_numeric' => '334'],
		['country_name' =>  'Holy see (vatican city state)', 'iso_code' => 'VA', 'iso_code_numeric' => '336'],
		['country_name' =>  'Honduras', 'iso_code' => 'HN', 'iso_code_numeric' => '340'],
		['country_name' =>  'Hong kong', 'iso_code' => 'HK', 'iso_code_numeric' => '344'],
		['country_name' =>  'Hungary', 'iso_code' => 'HU', 'iso_code_numeric' => '348'],
		['country_name' =>  'Iceland', 'iso_code' => 'IS', 'iso_code_numeric' => '352'],
		['country_name' =>  'India', 'iso_code' => 'IN', 'iso_code_numeric' => '356'],
		['country_name' =>  'Indonesia', 'iso_code' => 'ID', 'iso_code_numeric' => '360'],
		['country_name' =>  'Iran, islamic republic of', 'iso_code' => 'IR', 'iso_code_numeric' => '364'],
		['country_name' =>  'Iraq', 'iso_code' => 'IQ', 'iso_code_numeric' => '368'],
		['country_name' =>  'Ireland', 'iso_code' => 'IE', 'iso_code_numeric' => '372'],
		['country_name' =>  'Isle of man', 'iso_code' => 'IM', 'iso_code_numeric' => '833'],
		['country_name' =>  'Israel', 'iso_code' => 'IL', 'iso_code_numeric' => '376'],
		['country_name' =>  'Italy', 'iso_code' => 'IT', 'iso_code_numeric' => '380'],
		['country_name' =>  'Jamaica', 'iso_code' => 'JM', 'iso_code_numeric' => '388'],
		['country_name' =>  'Japan', 'iso_code' => 'JP', 'iso_code_numeric' => '392'],
		['country_name' =>  'Jersey', 'iso_code' => 'JE', 'iso_code_numeric' => '832'],
		['country_name' =>  'Jordan', 'iso_code' => 'JO', 'iso_code_numeric' => '400'],
		['country_name' =>  'Kazakhstan', 'iso_code' => 'KZ', 'iso_code_numeric' => '398'],
		['country_name' =>  'Kenya', 'iso_code' => 'KE', 'iso_code_numeric' => '404'],
		['country_name' =>  'Kiribati', 'iso_code' => 'KI', 'iso_code_numeric' => '296'],
		['country_name' =>  'Korea, democratic people\'s republic of', 'iso_code' => 'KP', 'iso_code_numeric' => '408'],
		['country_name' =>  'Korea, republic of', 'iso_code' =>  'KR', 'iso_code_numeric' => '410'],
		['country_name' =>  'Kuwait', 'iso_code' => 'KW', 'iso_code_numeric' => '414'],
		['country_name' =>  'Kyrgyzstan', 'iso_code' => 'KG', 'iso_code_numeric' => '417'],
		['country_name' =>  'Lao people\'s democratic republic', 'iso_code' => 'LA', 'iso_code_numeric' => '418'],
		['country_name' =>  'Latvia', 'iso_code' => 'LV', 'iso_code_numeric' => '428'],
		['country_name' =>  'Lebanon', 'iso_code' => 'LB', 'iso_code_numeric' => '422'],
		['country_name' =>  'Lesotho', 'iso_code' => 'LS', 'iso_code_numeric' => '426'],
		['country_name' =>  'Liberia', 'iso_code' => 'LR', 'iso_code_numeric' => '430'],
		['country_name' =>  'Libya', 'iso_code' => 'LY', 'iso_code_numeric' => '434'],
		['country_name' =>  'Liechtenstein', 'iso_code' => 'LI', 'iso_code_numeric' => '438'],
		['country_name' =>  'Lithuania', 'iso_code' => 'LT', 'iso_code_numeric' => '440'],
		['country_name' =>  'Luxembourg', 'iso_code' => 'LU', 'iso_code_numeric' => '442'],
		['country_name' =>  'Macao', 'iso_code' => 'MO', 'iso_code_numeric' => '446'],
		['country_name' =>  'Macedonia, the former yugoslav republic of', 'iso_code' => 'MK', 'iso_code_numeric' => '807'],
		['country_name' =>  'Madagascar', 'iso_code' => 'MG', 'iso_code_numeric' => '450'],
		['country_name' =>  'Malawi', 'iso_code' => 'MW', 'iso_code_numeric' => '454'],
		['country_name' =>  'Malaysia', 'iso_code' => 'MY', 'iso_code_numeric' => '458'],
		['country_name' =>  'Maldives', 'iso_code' => 'MV', 'iso_code_numeric' => '462'],
		['country_name' =>  'Mali', 'iso_code' => 'ML', 'iso_code_numeric' => '466'],
		['country_name' =>  'Malta', 'iso_code' => 'MT', 'iso_code_numeric' => '470'],
		['country_name' =>  'Marshall islands', 'iso_code' => 'MH', 'iso_code_numeric' => '584'],
		['country_name' =>  'Martinique', 'iso_code' => 'MQ', 'iso_code_numeric' => '474'],
		['country_name' =>  'Mauritania', 'iso_code' => 'MR', 'iso_code_numeric' => '478'],
		['country_name' =>  'Mauritius', 'iso_code' => 'MU', 'iso_code_numeric' => '480'],
		['country_name' =>  'Mayotte', 'iso_code' => 'YT', 'iso_code_numeric' => '175'],
		['country_name' =>  'Mexico', 'iso_code' => 'MX', 'iso_code_numeric' => '484'],
		['country_name' =>  'Micronesia, federated states of', 'iso_code' => 'FM', 'iso_code_numeric' => '583'],
		['country_name' =>  'Moldova, republic of', 'iso_code' => 'MD', 'iso_code_numeric' => '498'],
		['country_name' =>  'Monaco', 'iso_code' => 'MC', 'iso_code_numeric' => '492'],
		['country_name' =>  'Mongolia', 'iso_code' => 'MN', 'iso_code_numeric' => '496'],
		['country_name' =>  'Montenegro', 'iso_code' => 'ME', 'iso_code_numeric' => '499'],
		['country_name' =>  'Montserrat', 'iso_code' => 'MS', 'iso_code_numeric' => '500'],
		['country_name' =>  'Morocco', 'iso_code' => 'MA', 'iso_code_numeric' => '504'],
		['country_name' =>  'Mozambique', 'iso_code' => 'MZ', 'iso_code_numeric' => '508'],
		['country_name' =>  'Myanmar', 'iso_code' => 'MM', 'iso_code_numeric' => '104'],
		['country_name' =>  'Namibia', 'iso_code' => 'NA', 'iso_code_numeric' => '516'],
		['country_name' =>  'Nauru', 'iso_code' => 'NR', 'iso_code_numeric' => '520'],
		['country_name' =>  'Nepal', 'iso_code' => 'NP', 'iso_code_numeric' => '524'],
		['country_name' =>  'Netherlands', 'iso_code' => 'NL', 'iso_code_numeric' => '528'],
		['country_name' =>  'New caledonia', 'iso_code' => 'NC', 'iso_code_numeric' => '540'],
		['country_name' =>  'New zealand', 'iso_code' => 'NZ', 'iso_code_numeric' => '554'],
		['country_name' =>  'Nicaragua', 'iso_code' => 'NI', 'iso_code_numeric' => '558'],
		['country_name' =>  'Niger', 'iso_code' => 'NE', 'iso_code_numeric' => '562'],
		['country_name' =>  'Nigeria', 'iso_code' => 'NG', 'iso_code_numeric' => '566'],
		['country_name' =>  'Niue', 'iso_code' => 'NU', 'iso_code_numeric' => '570'],
		['country_name' =>  'Norfolk island', 'iso_code' => 'NF', 'iso_code_numeric' => '574'],
		['country_name' =>  'Northern mariana islands', 'iso_code' => 'MP', 'iso_code_numeric' => '580'],
		['country_name' =>  'Norway', 'iso_code' => 'NO', 'iso_code_numeric' => '578'],
		['country_name' =>  'Oman', 'iso_code' => 'OM', 'iso_code_numeric' => '512'],
		['country_name' =>  'Pakistan', 'iso_code' => 'PK', 'iso_code_numeric' => '586'],
		['country_name' =>  'Palau', 'iso_code' => 'PW', 'iso_code_numeric' => '585'],
		['country_name' =>  'Palestine, state of', 'iso_code' => 'PS', 'iso_code_numeric' => '275'],
		['country_name' =>  'Panama', 'iso_code' => 'PA', 'iso_code_numeric' => '591'],
		['country_name' =>  'Papua new guinea', 'iso_code' => 'PG', 'iso_code_numeric' => '598'],
		['country_name' =>  'Paraguay', 'iso_code' => 'PY', 'iso_code_numeric' => '600'],
		['country_name' =>  'Peru', 'iso_code' => 'PE', 'iso_code_numeric' => '604'],
		['country_name' =>  'Philippines', 'iso_code' => 'PH', 'iso_code_numeric' => '608'],
		['country_name' =>  'Pitcairn', 'iso_code' => 'PN', 'iso_code_numeric' => '612'],
		['country_name' =>  'Poland', 'iso_code' => 'PL', 'iso_code_numeric' => '616'],
		['country_name' =>  'Portugal', 'iso_code' => 'PT', 'iso_code_numeric' => '620'],
		['country_name' =>  'Puerto rico', 'iso_code' => 'PR', 'iso_code_numeric' => '630'],
		['country_name' =>  'Qatar', 'iso_code' => 'QA', 'iso_code_numeric' => '634'],
		['country_name' =>  'Réunion', 'iso_code' => 'RE', 'iso_code_numeric' => '638'],
		['country_name' =>  'Romania', 'iso_code' => 'RO', 'iso_code_numeric' => '642'],
		['country_name' =>  'Russian federation', 'iso_code' => 'RU', 'iso_code_numeric' => '643'],
		['country_name' =>  'Rwanda', 'iso_code' => 'RW', 'iso_code_numeric' => '646'],
		['country_name' =>  'Saint barthélemy', 'iso_code' => 'BL', 'iso_code_numeric' => '652'],
		['country_name' =>  'Saint helena, ascension and tristan da cunha', 'iso_code' => 'SH', 'iso_code_numeric' => '654'],
		['country_name' =>  'Saint kitts and nevis', 'iso_code' => 'KN', 'iso_code_numeric' => '659'],
		['country_name' =>  'Saint lucia', 'iso_code' => 'LC', 'iso_code_numeric' => '662'],
		['country_name' =>  'Saint martin (french part)', 'iso_code' => 'MF', 'iso_code_numeric' => '663'],
		['country_name' =>  'Saint pierre and miquelon', 'iso_code' => 'PM', 'iso_code_numeric' => '666'],
		['country_name' =>  'Saint vincent and the grenadines', 'iso_code' => 'VC', 'iso_code_numeric' => '670'],
		['country_name' =>  'Samoa', 'iso_code' => 'WS', 'iso_code_numeric' => '882'],
		['country_name' =>  'San marino', 'iso_code' => 'SM', 'iso_code_numeric' => '674'],
		['country_name' =>  'Sao tome and principe', 'iso_code' => 'ST', 'iso_code_numeric' => '678'],
		['country_name' =>  'Saudi arabia', 'iso_code' => 'SA', 'iso_code_numeric' => '682'],
		['country_name' =>  'Senegal', 'iso_code' => 'SN', 'iso_code_numeric' => '686'],
		['country_name' =>  'Serbia', 'iso_code' => 'RS', 'iso_code_numeric' => '688'],
		['country_name' =>  'Seychelles', 'iso_code' => 'SC', 'iso_code_numeric' => '690'],
		['country_name' =>  'Sierra leone', 'iso_code' => 'SL', 'iso_code_numeric' => '694'],
		['country_name' =>  'Singapore', 'iso_code' => 'SG', 'iso_code_numeric' => '702'],
		['country_name' =>  'Sint maarten (dutch part)', 'iso_code' => 'SX', 'iso_code_numeric' => '534'],
		['country_name' =>  'Slovakia', 'iso_code' => 'SK', 'iso_code_numeric' => '703'],
		['country_name' =>  'Slovenia', 'iso_code' => 'SI', 'iso_code_numeric' => '705'],
		['country_name' =>  'Solomon islands', 'iso_code' => 'SB', 'iso_code_numeric' => '090'],
		['country_name' =>  'Somalia', 'iso_code' => 'SO', 'iso_code_numeric' => '706'],
		['country_name' =>  'South africa', 'iso_code' => 'ZA', 'iso_code_numeric' => '710'],
		['country_name' =>  'South georgia and the south sandwich islands', 'iso_code' => 'GS', 'iso_code_numeric' => '239'],
		['country_name' =>  'South sudan', 'iso_code' => 'SS', 'iso_code_numeric' => '728'],
		['country_name' =>  'Spain', 'iso_code' => 'ES', 'iso_code_numeric' => '724'],
		['country_name' =>  'Sri lanka', 'iso_code' => 'LK', 'iso_code_numeric' => '144'],
		['country_name' =>  'Sudan', 'iso_code' => 'SD', 'iso_code_numeric' => '729'],
		['country_name' =>  'Suriname', 'iso_code' => 'SR', 'iso_code_numeric' => '740'],
		['country_name' =>  'Svalbard and jan mayen', 'iso_code' => 'SJ', 'iso_code_numeric' => '744'],
		['country_name' =>  'Swaziland', 'iso_code' => 'SZ', 'iso_code_numeric' => '748'],
		['country_name' =>  'Sweden', 'iso_code' => 'SE', 'iso_code_numeric' => '752'],
		['country_name' =>  'Switzerland', 'iso_code' => 'CH', 'iso_code_numeric' => '756'],
		['country_name' =>  'Syrian arab republic', 'iso_code' => 'SY', 'iso_code_numeric' => '760'],
		['country_name' =>  'Taiwan, province of china', 'iso_code' => 'TW', 'iso_code_numeric' => '158'],
		['country_name' =>  'Tajikistan', 'iso_code' => 'TJ', 'iso_code_numeric' => '762'],
		['country_name' =>  'Tanzania, united republic of', 'iso_code' => 'TZ', 'iso_code_numeric' => '834'],
		['country_name' =>  'Thailand', 'iso_code' => 'TH', 'iso_code_numeric' => '764'],
		['country_name' =>  'Timor-leste', 'iso_code' => 'TL', 'iso_code_numeric' => '626'],
		['country_name' =>  'Togo', 'iso_code' => 'TG', 'iso_code_numeric' => '768'],
		['country_name' =>  'Tokelau', 'iso_code' => 'TK', 'iso_code_numeric' => '772'],
		['country_name' =>  'Tonga', 'iso_code' => 'TO', 'iso_code_numeric' => '776'],
		['country_name' =>  'Trinidad and tobago', 'iso_code' => 'TT', 'iso_code_numeric' => '780'],
		['country_name' =>  'Tunisia', 'iso_code' => 'TN', 'iso_code_numeric' => '788'],
		['country_name' =>  'Turkey', 'iso_code' => 'TR', 'iso_code_numeric' => '792'],
		['country_name' =>  'Turkmenistan', 'iso_code' => 'TM', 'iso_code_numeric' => '795'],
		['country_name' =>  'Turks and caicos islands', 'iso_code' => 'TC', 'iso_code_numeric' => '796'],
		['country_name' =>  'Tuvalu', 'iso_code' => 'TV', 'iso_code_numeric' => '798'],
		['country_name' =>  'Uganda', 'iso_code' => 'UG', 'iso_code_numeric' => '800'],
		['country_name' =>  'Ukraine', 'iso_code' => 'UA', 'iso_code_numeric' => '804'],
		['country_name' =>  'United arab emirates', 'iso_code' => 'AE', 'iso_code_numeric' => '784'],
		['country_name' =>  'United kingdom', 'iso_code' => 'GB', 'iso_code_numeric' => '826'],
		['country_name' =>  'United states', 'iso_code' => 'US', 'iso_code_numeric' => '840'],
		['country_name' =>  'United states minor outlying islands', 'iso_code' => 'UM', 'iso_code_numeric' => '581'],
		['country_name' =>  'Uruguay', 'iso_code' => 'UY', 'iso_code_numeric' => '858'],
		['country_name' =>  'Uzbekistan', 'iso_code' => 'UZ', 'iso_code_numeric' => '860'],
		['country_name' =>  'Vanuatu', 'iso_code' => 'VU', 'iso_code_numeric' => '548'],
		['country_name' =>  'Venezuela, bolivarian republic of', 'iso_code' => 'VE', 'iso_code_numeric' => '862'],
		['country_name' =>  'Viet nam', 'iso_code' => 'VN', 'iso_code_numeric' => '704'],
		['country_name' =>  'Virgin islands, british', 'iso_code' => 'VG', 'iso_code_numeric' => '092'],
		['country_name' =>  'Virgin islands, u.s.', 'iso_code' => 'VI', 'iso_code_numeric' => '850'],
		['country_name' =>  'Wallis and futuna', 'iso_code' => 'WF', 'iso_code_numeric' => '876'],
		['country_name' =>  'Western sahara', 'iso_code' => 'EH', 'iso_code_numeric' => '732'],
		['country_name' =>  'Yemen', 'iso_code' => 'YE', 'iso_code_numeric' => '887'],
		['country_name' =>  'Zambia', 'iso_code' => 'ZM', 'iso_code_numeric' => '894'],
		['country_name' =>  'Zimbabwe', 'iso_code' => 'ZW', 'iso_code_numeric' => '716'],
		['country_name' =>  'Burma', 'iso_code' => 'BU','iso_code_numeric' =>  NULL],
		['country_name' =>  'East Timor', 'iso_code' => 'TP','iso_code_numeric' =>  NULL],
		['country_name' =>  'Netherlands Antilles', 'iso_code' => 'AN','iso_code_numeric' =>  NULL],
		['country_name' =>  'Yugoslavia', 'iso_code' => 'YU','iso_code_numeric' =>  NULL]
	];



    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		foreach ($this->_countries as $country)
		{
			DB::table('countries')->insert([
				'country_name' => $country['country_name'],
				'iso_code' => $country['iso_code'],
				'iso_code_numeric' => $country['iso_code_numeric'],
			]);
		}
    }
}
